-- =============================================================================
-- COLE ESTE ARQUIVO INTEIRO no Supabase: SQL Editor → New query → Run
-- Corrige: "relation public.cs_gestores does not exist"
-- Cria tabelas que faltam + RLS + função can_cs_view_client (painel /cs)
-- Pode rodar mais de uma vez (idempotente na maior parte).
-- =============================================================================

-- 1) Tabela cliente_gestores (cliente ↔ gestor, vários gestores por cliente)
create table if not exists public.cliente_gestores (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cliente_id, gestor_id)
);

create index if not exists idx_cliente_gestores_cliente_id on public.cliente_gestores(cliente_id);
create index if not exists idx_cliente_gestores_gestor_id on public.cliente_gestores(gestor_id);

-- Copia vínculos antigos de gestor_clientes → cliente_gestores (se existir a tabela antiga)
do $$
begin
  if to_regclass('public.gestor_clientes') is not null then
    insert into public.cliente_gestores (cliente_id, gestor_id)
    select gc.cliente_id, gc.gestor_id
    from public.gestor_clientes gc
    on conflict (cliente_id, gestor_id) do nothing;
  end if;
end $$;

-- 2) Gestor pode gerir cliente: usa cliente_gestores (precisa de public.is_admin() já existir)
create or replace function public.can_manage_client(target_cliente_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    auth.uid() = target_cliente_id
    or public.is_admin()
    or exists (
      select 1
      from public.cliente_gestores cg
      where cg.gestor_id = auth.uid()
        and cg.cliente_id = target_cliente_id
    ),
    false
  );
$$;

-- 3) Tabela cs_gestores (qual CS supervisiona qual gestor)
create table if not exists public.cs_gestores (
  id bigint generated by default as identity primary key,
  cs_id uuid not null references auth.users(id) on delete cascade,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cs_id, gestor_id)
);

create index if not exists idx_cs_gestores_cs_id on public.cs_gestores(cs_id);
create index if not exists idx_cs_gestores_gestor_id on public.cs_gestores(gestor_id);

create or replace function public.can_cs_manage_gestor(target_gestor_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.is_admin()
    or exists (
      select 1
      from public.cs_gestores cg
      where cg.cs_id = auth.uid()
        and cg.gestor_id = target_gestor_id
    ),
    false
  );
$$;

-- 4) RLS cliente_gestores
alter table public.cliente_gestores enable row level security;

drop policy if exists cliente_gestores_select on public.cliente_gestores;
create policy cliente_gestores_select on public.cliente_gestores
  for select
  using (
    public.is_admin()
    or gestor_id = auth.uid()
    or cliente_id = auth.uid()
  );

drop policy if exists cliente_gestores_insert on public.cliente_gestores;
create policy cliente_gestores_insert on public.cliente_gestores
  for insert
  with check (
    public.is_admin()
    or (gestor_id = auth.uid())
  );

drop policy if exists cliente_gestores_update on public.cliente_gestores;
create policy cliente_gestores_update on public.cliente_gestores
  for update
  using (public.is_admin() or gestor_id = auth.uid())
  with check (public.is_admin() or gestor_id = auth.uid());

drop policy if exists cliente_gestores_delete on public.cliente_gestores;
create policy cliente_gestores_delete on public.cliente_gestores
  for delete
  using (public.is_admin() or gestor_id = auth.uid());

-- 5) RLS cs_gestores (admin cadastra vínculos; CS só lê o próprio)
alter table public.cs_gestores enable row level security;

drop policy if exists cs_gestores_select on public.cs_gestores;
create policy cs_gestores_select on public.cs_gestores
  for select
  using (cs_id = auth.uid() or public.is_admin());

drop policy if exists cs_gestores_insert on public.cs_gestores;
create policy cs_gestores_insert on public.cs_gestores
  for insert
  with check (public.is_admin());

drop policy if exists cs_gestores_update on public.cs_gestores;
create policy cs_gestores_update on public.cs_gestores
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists cs_gestores_delete on public.cs_gestores;
create policy cs_gestores_delete on public.cs_gestores
  for delete
  using (public.is_admin());

-- 6) CS pode “ver” cliente supervisionado (função usada em policies + SECURITY DEFINER)
-- Só usa cliente_gestores (dados legados de gestor_clientes foram copiados acima, se existiam).
create or replace function public.can_cs_view_client(target_cliente_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.is_admin()
    or exists (
      select 1
      from public.cs_gestores cg
      inner join public.cliente_gestores cg2 on cg2.gestor_id = cg.gestor_id
      where cg.cs_id = auth.uid()
        and cg2.cliente_id = target_cliente_id
    ),
    false
  );
$$;

grant execute on function public.can_cs_view_client(uuid) to authenticated;

-- 7) CS lê vínculos dos gestores da equipe (dashboard /cs)
drop policy if exists cliente_gestores_select_cs_team on public.cliente_gestores;
create policy cliente_gestores_select_cs_team on public.cliente_gestores
  for select
  using (
    exists (
      select 1
      from public.cs_gestores cg
      where cg.cs_id = auth.uid()
        and cg.gestor_id = gestor_id
    )
  );

-- Policy em gestor_clientes só se a tabela existir (projeto legado)
do $$
begin
  if to_regclass('public.gestor_clientes') is not null then
    execute 'drop policy if exists gestor_clientes_select_cs_team on public.gestor_clientes';
    execute 'create policy gestor_clientes_select_cs_team on public.gestor_clientes
      for select
      using (
        exists (
          select 1
          from public.cs_gestores cg
          where cg.cs_id = auth.uid()
            and cg.gestor_id = gestor_id
        )
      )';
  end if;
end $$;

-- =============================================================================
-- Depois do Run: cadastre vínculos CS ↔ gestor (como admin no SQL ou Table Editor)
-- insert into public.cs_gestores (cs_id, gestor_id) values
--   ('UUID_DO_USUARIO_CS', 'UUID_DO_GESTOR');
-- =============================================================================

select 'OK: cs_gestores + cliente_gestores + RLS + can_cs_view_client aplicados.' as resultado;
