-- ============================================================
-- Cole este script no Supabase: SQL Editor → New query → Run
-- Cria a tabela gestor_clientes e permite gestor vincular cliente
-- ============================================================

-- 1) Coluna role em perfis (se ainda não existir)
alter table if exists public.perfis
  add column if not exists role text not null default 'user'
  check (role in ('user', 'premium_user', 'gestor', 'admin'));

-- 2) Tabela gestor_clientes
create table if not exists public.gestor_clientes (
  id bigint generated by default as identity primary key,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cliente_id)
);

create index if not exists idx_gestor_clientes_gestor_id on public.gestor_clientes(gestor_id);

-- 3) Funções usadas pelas policies
create or replace function public.current_user_role()
returns text language sql stable security definer set search_path = public
as $$ select coalesce((select p.role from public.perfis p where p.usuario_id = auth.uid() limit 1), 'user'); $$;

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select coalesce(public.current_user_role() = 'admin', false); $$;

-- 4) RLS na tabela
alter table public.gestor_clientes enable row level security;

-- 5) Policies: gestor vê só os seus; gestor pode inserir (vincular) para si
drop policy if exists gestor_clientes_select_own_or_admin on public.gestor_clientes;
create policy gestor_clientes_select_own_or_admin on public.gestor_clientes
  for select using (gestor_id = auth.uid() or public.is_admin());

drop policy if exists gestor_clientes_insert_admin_only on public.gestor_clientes;
drop policy if exists gestor_clientes_insert_own_or_admin on public.gestor_clientes;
create policy gestor_clientes_insert_own_or_admin on public.gestor_clientes
  for insert with check (gestor_id = auth.uid() or public.is_admin());

drop policy if exists gestor_clientes_update_admin_only on public.gestor_clientes;
create policy gestor_clientes_update_admin_only on public.gestor_clientes
  for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists gestor_clientes_delete_admin_only on public.gestor_clientes;
create policy gestor_clientes_delete_admin_only on public.gestor_clientes
  for delete using (public.is_admin());

-- Pronto. Depois de rodar, tente vincular o cliente de novo no app.
select 'gestor_clientes criada e policies aplicadas.' as resultado;
