-- Smart Award Finder: rotas premium e preferências do usuário.
-- Saldos vêm de programas_cliente (programa = program_id/program_name, saldo, custo_medio_milheiro, cliente_id).
--
-- rotas_premium: campos essenciais incluem classe e regiao_destino.
-- Exemplo:
--   origem | destino | programa     | classe    | milhas_necessarias | regiao_destino
--   GRU    | LIS     | LATAM Pass   | Executiva | 88000              | Europa
--   GRU    | MIA     | Smiles       | Executiva | 70000              | Estados Unidos
--   GRU    | SSA     | LATAM Pass   | Econômica | 12000              | Nordeste

-- Rotas premium (tabela de referência de resgates)
create table if not exists public.rotas_premium (
  id bigint generated by default as identity primary key,
  origem text not null,
  destino text not null,
  programa text not null,
  classe text not null,
  milhas_necessarias numeric not null default 0,
  taxas_embarque numeric not null default 0,
  valor_tarifa_pagante numeric not null default 0,
  regiao_destino text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_rotas_premium_programa on public.rotas_premium(programa);
create index if not exists idx_rotas_premium_regiao_destino on public.rotas_premium(regiao_destino);
create index if not exists idx_rotas_premium_classe on public.rotas_premium(classe);

alter table public.rotas_premium enable row level security;

-- Leitura pública (apenas consulta; inserção/atualização por admin ou função)
drop policy if exists rotas_premium_select_public on public.rotas_premium;
create policy rotas_premium_select_public on public.rotas_premium
  for select using (true);

drop policy if exists rotas_premium_insert_admin on public.rotas_premium;
create policy rotas_premium_insert_admin on public.rotas_premium
  for insert with check (public.is_admin());

drop policy if exists rotas_premium_update_admin on public.rotas_premium;
create policy rotas_premium_update_admin on public.rotas_premium
  for update using (public.is_admin());

drop policy if exists rotas_premium_delete_admin on public.rotas_premium;
create policy rotas_premium_delete_admin on public.rotas_premium
  for delete using (public.is_admin());

-- Preferências do usuário para sugestões inteligentes
create table if not exists public.preferencias_usuario (
  id uuid primary key default gen_random_uuid(),
  usuario_id uuid not null references auth.users(id) on delete cascade,
  preferencia_destino text[] not null default '{}',
  preferencia_classe text not null default 'Todas',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (usuario_id)
);

create index if not exists idx_preferencias_usuario_usuario_id on public.preferencias_usuario(usuario_id);

alter table public.preferencias_usuario enable row level security;

drop policy if exists preferencias_usuario_select_own on public.preferencias_usuario;
create policy preferencias_usuario_select_own on public.preferencias_usuario
  for select using (
    auth.uid() = usuario_id
    or public.can_manage_client(usuario_id)
  );

drop policy if exists preferencias_usuario_insert_own on public.preferencias_usuario;
create policy preferencias_usuario_insert_own on public.preferencias_usuario
  for insert with check (auth.uid() = usuario_id);

drop policy if exists preferencias_usuario_update_own on public.preferencias_usuario;
create policy preferencias_usuario_update_own on public.preferencias_usuario
  for update using (auth.uid() = usuario_id)
  with check (auth.uid() = usuario_id);

drop policy if exists preferencias_usuario_delete_own on public.preferencias_usuario;
create policy preferencias_usuario_delete_own on public.preferencias_usuario
  for delete using (auth.uid() = usuario_id);
