revoke delete, insert, update on table public.audit_logs from authenticated;
revoke delete, update on table public.balcao_consumos from authenticated;
revoke delete on table public.cotacoes from authenticated;
revoke update on table public.csat_avaliacoes from authenticated;
revoke delete on table public.demandas_cliente from authenticated;
revoke delete, insert, update on table public.dupla_scores from authenticated;
revoke delete, insert, update on table public.equipes_duplas from authenticated;
revoke delete, insert, update on table public.gestor_scores from authenticated;
revoke delete, insert on table public.insights_cliente from authenticated;
revoke delete, insert on table public.notificacoes from authenticated;
revoke update on table public.nps_avaliacoes from authenticated;
revoke delete on table public.nps_convites from authenticated;
revoke delete on table public.perfis from authenticated;
revoke delete on table public.perfis_configuracao from authenticated;
revoke delete on table public.pesquisa_passagens_config from authenticated;
revoke delete on table public.pesquisa_passagens_uso_equipe from authenticated;
revoke delete on table public.pesquisa_passagens_uso_usuario from authenticated;
revoke update on table public.reunioes_onboarding_participantes from authenticated;
revoke delete on table public.tarefas_cs from authenticated;
revoke delete, insert, update on table public.timeline_eventos from authenticated;
