-- Role system: admin, cs, gestor, cliente.
-- Many-to-many: cliente_gestores (a client can have multiple gestores).
-- CS: cs_gestores (which gestores are assigned to a CS user).

-- 1) Normalize existing roles to new set and update check
update public.perfis
set role = 'cliente'
where role in ('user', 'premium_user');

do $$
declare
  c name;
begin
  for c in
    select conname from pg_constraint
    where conrelid = 'public.perfis'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%role%'
  loop
    execute format('alter table public.perfis drop constraint %I', c);
  end loop;
end $$;

alter table public.perfis
  add constraint perfis_role_check
  check (role in ('admin', 'cs', 'gestor', 'cliente'));

-- 2) Many-to-many: client can have multiple gestores
create table if not exists public.cliente_gestores (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cliente_id, gestor_id)
);

create index if not exists idx_cliente_gestores_cliente_id on public.cliente_gestores(cliente_id);
create index if not exists idx_cliente_gestores_gestor_id on public.cliente_gestores(gestor_id);

-- Migrate from gestor_clientes (if table exists)
insert into public.cliente_gestores (cliente_id, gestor_id)
select gc.cliente_id, gc.gestor_id
from public.gestor_clientes gc
on conflict (cliente_id, gestor_id) do nothing;

-- 3) can_manage_client: use cliente_gestores
create or replace function public.can_manage_client(target_cliente_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    auth.uid() = target_cliente_id
    or public.is_admin()
    or exists (
      select 1
      from public.cliente_gestores cg
      where cg.gestor_id = auth.uid()
        and cg.cliente_id = target_cliente_id
    ),
    false
  );
$$;

-- 4) CS: which gestores are assigned to this CS user
create table if not exists public.cs_gestores (
  id bigint generated by default as identity primary key,
  cs_id uuid not null references auth.users(id) on delete cascade,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cs_id, gestor_id)
);

create index if not exists idx_cs_gestores_cs_id on public.cs_gestores(cs_id);
create index if not exists idx_cs_gestores_gestor_id on public.cs_gestores(gestor_id);

-- 5) CS can manage (view/edit) a gestor if assigned
create or replace function public.can_cs_manage_gestor(target_gestor_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    public.is_admin()
    or exists (
      select 1
      from public.cs_gestores cg
      where cg.cs_id = auth.uid()
        and cg.gestor_id = target_gestor_id
    ),
    false
  );
$$;

-- 6) RLS cliente_gestores
alter table public.cliente_gestores enable row level security;

drop policy if exists cliente_gestores_select on public.cliente_gestores;
create policy cliente_gestores_select on public.cliente_gestores
  for select
  using (
    public.is_admin()
    or gestor_id = auth.uid()
    or cliente_id = auth.uid()
  );

drop policy if exists cliente_gestores_insert on public.cliente_gestores;
create policy cliente_gestores_insert on public.cliente_gestores
  for insert
  with check (
    public.is_admin()
    or (gestor_id = auth.uid())
  );

drop policy if exists cliente_gestores_update on public.cliente_gestores;
create policy cliente_gestores_update on public.cliente_gestores
  for update
  using (public.is_admin() or gestor_id = auth.uid())
  with check (public.is_admin() or gestor_id = auth.uid());

drop policy if exists cliente_gestores_delete on public.cliente_gestores;
create policy cliente_gestores_delete on public.cliente_gestores
  for delete
  using (public.is_admin() or gestor_id = auth.uid());

-- 7) RLS cs_gestores (admin assigns; CS only reads own)
alter table public.cs_gestores enable row level security;

drop policy if exists cs_gestores_select on public.cs_gestores;
create policy cs_gestores_select on public.cs_gestores
  for select
  using (cs_id = auth.uid() or public.is_admin());

drop policy if exists cs_gestores_insert on public.cs_gestores;
create policy cs_gestores_insert on public.cs_gestores
  for insert
  with check (public.is_admin());

drop policy if exists cs_gestores_update on public.cs_gestores;
create policy cs_gestores_update on public.cs_gestores
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists cs_gestores_delete on public.cs_gestores;
create policy cs_gestores_delete on public.cs_gestores
  for delete
  using (public.is_admin());

-- 8) Perfis: CS can update gestor info (nome, etc.) for assigned gestores
drop policy if exists perfis_update_own_or_gestor_or_admin on public.perfis;
create policy perfis_update_own_or_gestor_or_admin on public.perfis
  for update
  using (
    auth.uid() = usuario_id
    or public.is_admin()
    or public.can_manage_client(usuario_id)
    or public.can_cs_manage_gestor(usuario_id)
  )
  with check (
    auth.uid() = usuario_id
    or public.is_admin()
    or public.can_manage_client(usuario_id)
    or public.can_cs_manage_gestor(usuario_id)
  );
