-- Demands opened by clients for their managers.
create table if not exists public.demandas_cliente (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  tipo text not null check (tipo in ('emissao', 'outros')),
  status text not null default 'pendente',
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_demandas_cliente_cliente_id
  on public.demandas_cliente(cliente_id);

create index if not exists idx_demandas_cliente_created_at
  on public.demandas_cliente(created_at desc);

alter table public.demandas_cliente enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demandas_cliente'
      and policyname = 'demandas_cliente_select_multi_tenant'
  ) then
    create policy demandas_cliente_select_multi_tenant
      on public.demandas_cliente
      for select
      using (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demandas_cliente'
      and policyname = 'demandas_cliente_insert_own'
  ) then
    create policy demandas_cliente_insert_own
      on public.demandas_cliente
      for insert
      with check (auth.uid() = cliente_id);
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'demandas_cliente'
      and policyname = 'demandas_cliente_update_manager_or_owner'
  ) then
    create policy demandas_cliente_update_manager_or_owner
      on public.demandas_cliente
      for update
      using (public.can_manage_client(cliente_id))
      with check (public.can_manage_client(cliente_id));
  end if;
end $$;
