-- Fix runtime errors found by authenticated client smoke:
-- 1) timeline_eventos_push exists but lost authenticated EXECUTE grant remotely.
-- 2) oportunidades_voo exists in local migrations but is missing from the remote Data API schema.

grant execute on function public.timeline_eventos_push(
  uuid,
  uuid,
  uuid,
  text,
  text,
  text,
  jsonb,
  timestamptz
) to authenticated;

create table if not exists public.oportunidades_voo (
  id bigint generated by default as identity primary key,
  origem text not null,
  destino text not null,
  programa text not null,
  classe text not null,
  milhas integer not null,
  data_voo date,
  valor_estimado numeric not null default 0,
  regiao_destino text,
  data_detectada timestamptz not null default now(),
  created_at timestamptz not null default now()
);

comment on table public.oportunidades_voo is 'Oportunidades de resgate com milhas (radar de ofertas)';
comment on column public.oportunidades_voo.valor_estimado is 'Valor estimado em reais (R$)';
comment on column public.oportunidades_voo.regiao_destino is 'Ex: Brasil, Europa, Estados Unidos, Asia';

create index if not exists idx_oportunidades_voo_programa on public.oportunidades_voo (programa);
create index if not exists idx_oportunidades_voo_regiao on public.oportunidades_voo (regiao_destino);
create index if not exists idx_oportunidades_voo_data_detectada on public.oportunidades_voo (data_detectada desc);

alter table public.oportunidades_voo enable row level security;

grant select on public.oportunidades_voo to anon, authenticated;

drop policy if exists oportunidades_voo_select_public on public.oportunidades_voo;
create policy oportunidades_voo_select_public on public.oportunidades_voo
  for select
  using (true);

drop policy if exists oportunidades_voo_insert_admin on public.oportunidades_voo;
create policy oportunidades_voo_insert_admin on public.oportunidades_voo
  for insert
  with check (public.is_admin());

drop policy if exists oportunidades_voo_update_admin on public.oportunidades_voo;
create policy oportunidades_voo_update_admin on public.oportunidades_voo
  for update
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists oportunidades_voo_delete_admin on public.oportunidades_voo;
create policy oportunidades_voo_delete_admin on public.oportunidades_voo
  for delete
  using (public.is_admin());
