-- Oportunidades de alto valor para resgate com milhas.
-- Exemplo: GRU → MAD, Smiles, Business, 74.000 milhas, valor estimado R$ 8.000.
-- Dados inseridos pelo sistema ou manualmente por admins.

create table if not exists public.oportunidades_voo (
  id bigint generated by default as identity primary key,
  origem text not null,
  destino text not null,
  programa text not null,
  classe text not null,
  milhas integer not null,
  data_voo date,
  valor_estimado numeric not null default 0,
  regiao_destino text,
  data_detectada timestamptz not null default now(),
  created_at timestamptz not null default now()
);

comment on table public.oportunidades_voo is 'Oportunidades de resgate com milhas (radar de ofertas)';
comment on column public.oportunidades_voo.valor_estimado is 'Valor estimado em reais (R$)';
comment on column public.oportunidades_voo.regiao_destino is 'Ex: Brasil, Europa, Estados Unidos, Asia';

create index if not exists idx_oportunidades_voo_programa on public.oportunidades_voo(programa);
create index if not exists idx_oportunidades_voo_regiao on public.oportunidades_voo(regiao_destino);
create index if not exists idx_oportunidades_voo_data_detectada on public.oportunidades_voo(data_detectada desc);

alter table public.oportunidades_voo enable row level security;

drop policy if exists oportunidades_voo_select_public on public.oportunidades_voo;
create policy oportunidades_voo_select_public on public.oportunidades_voo
  for select using (true);

drop policy if exists oportunidades_voo_insert_admin on public.oportunidades_voo;
create policy oportunidades_voo_insert_admin on public.oportunidades_voo
  for insert with check (public.is_admin());

drop policy if exists oportunidades_voo_update_admin on public.oportunidades_voo;
create policy oportunidades_voo_update_admin on public.oportunidades_voo
  for update using (public.is_admin());

drop policy if exists oportunidades_voo_delete_admin on public.oportunidades_voo;
create policy oportunidades_voo_delete_admin on public.oportunidades_voo
  for delete using (public.is_admin());
