-- Multi-tenant manager module (gestor) + audit + operational mileage tables.
-- Safe to run multiple times where possible.

alter table if exists public.perfis
  add column if not exists role text not null default 'user'
  check (role in ('user', 'premium_user', 'gestor', 'admin'));

create table if not exists public.gestor_clientes (
  id bigint generated by default as identity primary key,
  gestor_id uuid not null references auth.users(id) on delete cascade,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (cliente_id)
);

create table if not exists public.logs_acoes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  tipo_acao text not null,
  entidade_afetada text not null,
  entidade_id text,
  details jsonb not null default '{}'::jsonb,
  timestamp timestamptz not null default now()
);

create table if not exists public.programas_cliente (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  program_id text not null,
  program_name text not null,
  logo text,
  logo_color text,
  logo_image_url text,
  clube_nome text,
  saldo numeric not null default 0,
  custo_medio_milheiro numeric not null default 0,
  custo_saldo numeric not null default 0,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (cliente_id, program_id)
);

create table if not exists public.movimentos_programa (
  id bigint generated by default as identity primary key,
  programa_cliente_id bigint not null references public.programas_cliente(id) on delete cascade,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  data date not null default current_date,
  tipo text not null check (tipo in ('entrada', 'saida')),
  descricao text,
  milhas numeric not null default 0,
  economia_real numeric,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.lotes_programa (
  id bigint generated by default as identity primary key,
  programa_cliente_id bigint not null references public.programas_cliente(id) on delete cascade,
  cliente_id uuid not null references auth.users(id) on delete cascade,
  validade_lote date not null,
  quantidade numeric not null default 0,
  created_at timestamptz not null default now(),
  unique (programa_cliente_id, validade_lote)
);

create index if not exists idx_gestor_clientes_gestor_id on public.gestor_clientes(gestor_id);
create index if not exists idx_logs_acoes_user_id on public.logs_acoes(user_id);
create index if not exists idx_logs_acoes_timestamp on public.logs_acoes(timestamp desc);
create index if not exists idx_programas_cliente_cliente_id on public.programas_cliente(cliente_id);
create index if not exists idx_programas_cliente_updated_at on public.programas_cliente(updated_at desc);
create index if not exists idx_movimentos_programa_cliente_id on public.movimentos_programa(cliente_id);
create index if not exists idx_movimentos_programa_data on public.movimentos_programa(data desc);
create index if not exists idx_lotes_programa_cliente_id on public.lotes_programa(cliente_id);
create index if not exists idx_lotes_programa_validade on public.lotes_programa(validade_lote);

create or replace function public.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select p.role
  from public.perfis p
  where p.usuario_id = auth.uid()
  limit 1;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.current_user_role() = 'admin', false);
$$;

create or replace function public.can_manage_client(target_cliente_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    coalesce(
      auth.uid() = target_cliente_id
      or public.is_admin()
      or exists (
        select 1
        from public.gestor_clientes gc
        where gc.gestor_id = auth.uid()
          and gc.cliente_id = target_cliente_id
      ),
      false
    );
$$;

alter table public.gestor_clientes enable row level security;
alter table public.logs_acoes enable row level security;
alter table public.programas_cliente enable row level security;
alter table public.movimentos_programa enable row level security;
alter table public.lotes_programa enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'perfis' and policyname = 'perfis_select_public'
  ) then
    create policy perfis_select_public on public.perfis for select using (true);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'perfis' and policyname = 'perfis_insert_own'
  ) then
    create policy perfis_insert_own on public.perfis for insert with check (auth.uid() = usuario_id);
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'perfis' and policyname = 'perfis_update_own_or_admin'
  ) then
    create policy perfis_update_own_or_admin on public.perfis
      for update
      using (auth.uid() = usuario_id or public.is_admin())
      with check (auth.uid() = usuario_id or public.is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'gestor_clientes' and policyname = 'gestor_clientes_select_own_or_admin'
  ) then
    create policy gestor_clientes_select_own_or_admin on public.gestor_clientes
      for select
      using (gestor_id = auth.uid() or public.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'gestor_clientes' and policyname = 'gestor_clientes_insert_admin_only'
  ) then
    create policy gestor_clientes_insert_admin_only on public.gestor_clientes
      for insert with check (public.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'gestor_clientes' and policyname = 'gestor_clientes_update_admin_only'
  ) then
    create policy gestor_clientes_update_admin_only on public.gestor_clientes
      for update using (public.is_admin()) with check (public.is_admin());
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'gestor_clientes' and policyname = 'gestor_clientes_delete_admin_only'
  ) then
    create policy gestor_clientes_delete_admin_only on public.gestor_clientes
      for delete using (public.is_admin());
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'programas_cliente' and policyname = 'programas_cliente_select_multi_tenant'
  ) then
    create policy programas_cliente_select_multi_tenant on public.programas_cliente
      for select using (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'programas_cliente' and policyname = 'programas_cliente_insert_multi_tenant'
  ) then
    create policy programas_cliente_insert_multi_tenant on public.programas_cliente
      for insert with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'programas_cliente' and policyname = 'programas_cliente_update_multi_tenant'
  ) then
    create policy programas_cliente_update_multi_tenant on public.programas_cliente
      for update using (public.can_manage_client(cliente_id))
      with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'programas_cliente' and policyname = 'programas_cliente_delete_multi_tenant'
  ) then
    create policy programas_cliente_delete_multi_tenant on public.programas_cliente
      for delete using (public.can_manage_client(cliente_id));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'movimentos_programa' and policyname = 'movimentos_programa_select_multi_tenant'
  ) then
    create policy movimentos_programa_select_multi_tenant on public.movimentos_programa
      for select using (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'movimentos_programa' and policyname = 'movimentos_programa_insert_multi_tenant'
  ) then
    create policy movimentos_programa_insert_multi_tenant on public.movimentos_programa
      for insert with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'movimentos_programa' and policyname = 'movimentos_programa_update_multi_tenant'
  ) then
    create policy movimentos_programa_update_multi_tenant on public.movimentos_programa
      for update using (public.can_manage_client(cliente_id))
      with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'movimentos_programa' and policyname = 'movimentos_programa_delete_multi_tenant'
  ) then
    create policy movimentos_programa_delete_multi_tenant on public.movimentos_programa
      for delete using (public.can_manage_client(cliente_id));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lotes_programa' and policyname = 'lotes_programa_select_multi_tenant'
  ) then
    create policy lotes_programa_select_multi_tenant on public.lotes_programa
      for select using (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lotes_programa' and policyname = 'lotes_programa_insert_multi_tenant'
  ) then
    create policy lotes_programa_insert_multi_tenant on public.lotes_programa
      for insert with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lotes_programa' and policyname = 'lotes_programa_update_multi_tenant'
  ) then
    create policy lotes_programa_update_multi_tenant on public.lotes_programa
      for update using (public.can_manage_client(cliente_id))
      with check (public.can_manage_client(cliente_id));
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'lotes_programa' and policyname = 'lotes_programa_delete_multi_tenant'
  ) then
    create policy lotes_programa_delete_multi_tenant on public.lotes_programa
      for delete using (public.can_manage_client(cliente_id));
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'logs_acoes' and policyname = 'logs_acoes_select_multi_tenant'
  ) then
    create policy logs_acoes_select_multi_tenant on public.logs_acoes
      for select
      using (
        auth.uid() = user_id
        or public.is_admin()
        or exists (
          select 1
          from public.gestor_clientes gc
          where gc.gestor_id = auth.uid()
            and gc.cliente_id = user_id
        )
      );
  end if;

  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'logs_acoes' and policyname = 'logs_acoes_insert_authenticated'
  ) then
    create policy logs_acoes_insert_authenticated on public.logs_acoes
      for insert with check (auth.uid() is not null and auth.uid() = user_id);
  end if;
end $$;
