-- Tabela de preços de compra de milhas por programa.
-- Exemplo:
--   programa | preco_milheiro | bonus_percentual | data_promocao
--   Smiles  | 70              | 100              | 2026-03-10
-- Preço efetivo do milheiro (exemplo acima) = 70 / (1 + 1.00) = 35.

create table if not exists public.preco_compra_milhas (
  id bigint generated by default as identity primary key,
  programa text not null,
  preco_milheiro numeric not null default 0,      -- R$ por 1.000 milhas (sem bônus)
  bonus_percentual numeric not null default 0,    -- 100 = 100% bônus, 50 = 50% bônus
  data_promocao date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists idx_preco_compra_milhas_programa
  on public.preco_compra_milhas(programa);

alter table public.preco_compra_milhas enable row level security;

drop policy if exists preco_compra_milhas_select_public on public.preco_compra_milhas;
create policy preco_compra_milhas_select_public on public.preco_compra_milhas
  for select using (true);

drop policy if exists preco_compra_milhas_insert_admin on public.preco_compra_milhas;
create policy preco_compra_milhas_insert_admin on public.preco_compra_milhas
  for insert with check (public.is_admin());

drop policy if exists preco_compra_milhas_update_admin on public.preco_compra_milhas;
create policy preco_compra_milhas_update_admin on public.preco_compra_milhas
  for update using (public.is_admin());

drop policy if exists preco_compra_milhas_delete_admin on public.preco_compra_milhas;
create policy preco_compra_milhas_delete_admin on public.preco_compra_milhas
  for delete using (public.is_admin());

